name: Bug report
description: Report a bug
title: "[Bug] <title>"
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the problem you're reporting.
    options:
    - label: I have searched for existing issues and did not find anything like it
      required: true

- type: textarea
  attributes:
    label: Describe the bug
    description: |
       Please give a **clear** and **concise** description of what the bug is. If you have any files to upload that can be helpful as well.

      Tip: you can attach files by clicking the text area to highlight it and then click the link that says paste, drop or click to add files.
  validations:
    required: false

- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
        Please help us by explaining how to reproduce the bug in a step by step manner.

  validations:
    required: true


- type: textarea
  attributes:
    label: Expected behaviour
    description: |
        Please describe what you think it should be instead and why, as best you can (the more details you provide the better).

  validations:
    required: true

- type: textarea
  attributes:
    label: Environment
    description: |
      Example:
        - **OS**: macOS Sonoma 14.5
        - **Device**: MacBook Pro M1
        - **Browser**: Safari 17.5 (19618.2.12.11.6)

        **PLEASE** provide **AT** **LEAST** the above items. If you have the **SAME** problem with more than one device please list the above for **ALL** **RELEVANT** **devices** with **any** **relevant** **context**.
    value: |
        - OS:
        - Device:
        - Browser:
    render: markdown
  validations:
    required: true

- type: textarea
  attributes:
    label: bug_report.sh output
    description: |
      Please attach the log file of './bug_report.sh'.

      Tip: you can attach files by clicking the text area to highlight it and then click the link that says paste, drop or click to add files.
  validations:
    required: false

